language: go

go:
    - 1.3
    - 1.4
    - tip

before_script:
  - go list -f '{{range .TestImports}}{{.}} {{end}}' ./... | xargs go get -v
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  - if ! go get -v code.google.com/p/go.tools/cmd/cover; then go get -v golang.org/x/tools/cmd/cover; fi

script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
